# SENSOR : ALIAS
# tsens_tz_sensor4 : cpu1-3
# tsens_tz_sensor3 : cpu0-2
# tsens_tz_sensor0 : pop_mem

debug
#Conf file: /system/etc/thermal-engine.conf

[CPU0_MONITOR]
algo_type monitor
sensor xo_therm
sampling 10000
thresholds     56000
thresholds_clr 50000
actions        cpu
action_info    800000

[xo_therm_report]
algo_type monitor
sampling 10000
sensor xo_therm
thresholds     56000        60000		63000
thresholds_clr 50000        54000		57000
actions        report       report      report
action_info    1            2           3

[xo_therm_lcd]
algo_type monitor
sampling 10000
sensor xo_therm
thresholds     56000 
thresholds_clr 50000 
actions        lcd
action_info    108

[xo_therm_charge]
algo_type monitor
sensor xo_therm
sampling 10000
thresholds     56000
thresholds_clr 50000
actions        battery
action_info    1

